import { ProjectType } from "@/types";
import { TECHNOLOGIES } from "./technologies";


export const PROJECTS: ProjectType[] = [
  {
    id: "proj-001",
    title: "Game of Thrones Hub",
    description: "Sitio web con todas las temporadas, libros y reparto de Game of Thrones.",
    technologies: [TECHNOLOGIES.html, TECHNOLOGIES.css, TECHNOLOGIES.javascript],
    category: ["FRONTEND"],
    demoUrl: "https://got-v2.vercel.app/home",
    repoUrl: "https://github.com/PaulPPS632/GOT-V2",
    year: 2019,
    imageUrl: "/proyectos/got/home-got.webp",
    longDescription:
      "Hub para fans de Game of Thrones: permite ver los capítulos de las 8 temporadas y leer los libros de la saga Canción de Hielo y Fuego desde el mismo sitio. La navegación está organizada por temporada, con una grilla de capítulos con su banner y título, y una biblioteca de libros con lector integrado.",
    features: [
      "Navegación por las 8 temporadas con grilla de capítulos (banner + título).",
      "Reproductor de capítulos embebido con vista a pantalla completa.",
      "Biblioteca de libros de la saga con portadas.",
      "Lector integrado para leer cada libro dentro del sitio, con miniaturas y control de páginas.",
      "Página de inicio con sinopsis de la serie.",
      "Interfaz en modo oscuro y layout responsive.",
    ],
    media: [
      {
        type: "image",
        url: "/proyectos/got/home-got.webp",
        caption: "Inicio con sinopsis de la serie",
      },
      {
        type: "image",
        url: "/proyectos/got/temporadas-got.webp",
        caption: "Grilla de capítulos por temporada",
      },
      {
        type: "image",
        url: "/proyectos/got/reproductor-got.webp",
        caption: "Reproductor de capítulo",
      },
      {
        type: "image",
        url: "/proyectos/got/libros-got.webp",
        caption: "Biblioteca de libros de la saga",
      },
      {
        type: "image",
        url: "/proyectos/got/lector-got.webp",
        caption: "Lector de libros integrado",
      },
    ],
  },
  {
    id: "proj-002",
    title: "TechNet E-Commerce",
    description: "E-commerce desarrollado primero con Spring Boot y luego migrado a Angular + Express.",
    technologies: [TECHNOLOGIES.angular, TECHNOLOGIES.express, TECHNOLOGIES.springboot, TECHNOLOGIES.mysql],
    category: ["FULLSTACK"],
    demoUrl: "https://technetsac.com",
    year: 2023,
  },
  {
    id: "proj-003",
    title: "WhatsApp Marketing System",
    description: "Sistema de envío de mensajes promocionales usando colas con RabbitMQ y microservicios en Docker.",
    technologies: [TECHNOLOGIES.angular, TECHNOLOGIES.express, TECHNOLOGIES.rabbitmq, TECHNOLOGIES.docker],
    category: ["FULLSTACK"],
    repoUrl: "https://github.com/PaulPPS632/wsp-bot-ccd-ui",
    year: 2024,
  },
  {
    id: "proj-004",
    title: "File Manager R2",
    description: "Gestor de archivos con permisos por usuario, historial de acciones y almacenamiento en Cloudflare R2.",
    technologies: [TECHNOLOGIES.angular, TECHNOLOGIES.express, TECHNOLOGIES.r2, TECHNOLOGIES.postgresql],
    category: ["FULLSTACK"],
    repoUrl:"https://github.com/PaulPPS632/GESTOR-ARCHIVOS-CCD-UI",
    year: 2024,
  },
  {
    id: "proj-005",
    title: "Landing CCD",
    description: "Landing page en Astro como embudo de ventas para campañas de Meta y TikTok.",
    technologies: [TECHNOLOGIES.astro, TECHNOLOGIES.tailwind, TECHNOLOGIES.typescript],
    category: ["FRONTEND"],
    demoUrl:"https://curso.ccdcapacitacion.edu.pe/",
    repoUrl:"https://github.com/CCD-TI/SPA-CURSO",
    year: 2025,
  },
  {
    id: "proj-006",
    title: "PDF Certificate Generator",
    description: "Microservicio Node.js para generar certificados PDF a partir de plantillas JSON.",
    technologies: [TECHNOLOGIES.nodejs, TECHNOLOGIES.express, TECHNOLOGIES.json],
    category: ["BACKEND"],
    repoUrl:"https://github.com/PaulPPS632/Certificados",
    year: 2024,
  },
  {
    id: "proj-007",
    title: "Funcional Neuro Laboral Backend",
    description: "Backend con Node.js y Express para app de bienestar psicológico con IA.",
    technologies: [TECHNOLOGIES.nodejs, TECHNOLOGIES.express, TECHNOLOGIES.swagger, TECHNOLOGIES.postgresql],
    category: ["BACKEND"],
    year: 2025,
  },
  {
    id: "proj-008",
    title: "Kardex Cuadrado Electronics",
    description: "Software de escritorio en Java para gestión de inventario, facturación y trazabilidad de productos.",
    technologies: [TECHNOLOGIES.java, TECHNOLOGIES.mysql],
    category: ["BACKEND"],
    year: 2021,
    company: "Cuadrado Electronics",
    role: "FullStack Developer",
    imageUrl: "/experiencias/cuadrado/home-cuadrado.webp",
    longDescription:
      "Sistema de escritorio hecho en Java (NetBeans) para Cuadrado Electronics, desarrollado de forma autodidacta mientras trabajaba en el área de ventas. Cubre el kardex de inventario, la facturación y la trazabilidad de productos serializados, con integración a la API de facturación electrónica que usaba la empresa. Con él se hizo el primer inventario general digitalizado del negocio.",
    features: [
      "Kardex de inventario con manejo de productos serializados.",
      "Facturación integrada con la API de facturación electrónica de la empresa.",
      "Rastreo de productos por almacén y cantidad.",
      "Registro de clientes, usuarios y tipos de condición de pago (días de crédito).",
      "Control de correlativos iniciales por tipo de comprobante y empresa.",
      "Consultas de documentos con filtros por proveedor, estado y rango de fechas.",
      "Acceso por usuario con cargo/rol visible en sesión.",
    ],
    highlights: [
      "Primer inventario general digitalizado de la empresa, reduciendo errores manuales.",
      "Emisión de comprobantes automatizada gracias a la integración con facturación electrónica.",
    ],
    media: [
      {
        type: "image",
        url: "/experiencias/cuadrado/home-cuadrado.webp",
        caption: "Pantalla principal con los módulos del sistema",
      },
      {
        type: "image",
        url: "/experiencias/cuadrado/login-cuadrado.webp",
        caption: "Inicio de sesión",
      },
      {
        type: "image",
        url: "/experiencias/cuadrado/rastreo-producto-cuadrado.webp",
        caption: "Rastreo de productos en almacén",
      },
      {
        type: "image",
        url: "/experiencias/cuadrado/reporte-ventas-cuadrado.webp",
        caption: "Consulta de documentos por proveedor, estado y fechas",
      },
      {
        type: "image",
        url: "/experiencias/cuadrado/correlativo-cuadrado.webp",
        caption: "Cambio de correlativo inicial por tipo de comprobante",
      },
      {
        type: "image",
        url: "/experiencias/cuadrado/registro-clientes-cuadrado.webp",
        caption: "Registro de clientes",
      },
      {
        type: "image",
        url: "/experiencias/cuadrado/registro-condicion-cuadrado.webp",
        caption: "Registro de tipos de condición de pago",
      },
      {
        type: "image",
        url: "/experiencias/cuadrado/registro-usuario-cuadrado.webp",
        caption: "Registro de usuarios del sistema",
      },
    ],
  },
  {
    id: "proj-009",
    title: "PRFACT SaaS",
    description: "Aplicación SaaS de gestión de inventario y facturación con dashboards en tiempo real.",
    technologies: [TECHNOLOGIES.angular, TECHNOLOGIES.express, TECHNOLOGIES.postgresql, TECHNOLOGIES.docker],
    category: ["FULLSTACK"],
    demoUrl:"",
    year: 2025,
  },
  {
    id: "proj-010",
    title: "E-Learning CCD",
    description: "Plataforma de aprendizaje para Centro de Capacitación y Desarrollo con certificados masivos y gestión de cursos.",
    technologies: [TECHNOLOGIES.angular, TECHNOLOGIES.express, TECHNOLOGIES.nodejs, TECHNOLOGIES.postgresql],
    category: ["FULLSTACK"],
    year: 2024,
    demoUrl: "https://www.ccdcapacitacion.edu.pe",
    company: "Centro de Capacitación y Desarrollo",
    role: "Jefe de Área de TI",
    imageUrl: "/experiencias/ccd/plataforma-ccd.webp",
    longDescription:
      "Plataforma e-learning del Centro de Capacitación y Desarrollo: catálogo público de cursos y diplomas por escuela, aula virtual con reproducción de clases y un panel administrativo para gestionar todo el negocio académico.\n\nReemplazó una plataforma heredada y desorganizada por una arquitectura modular y desacoplada, que permite manejar cursos y salas de forma independiente. Dirigí el equipo de desarrollo desde el área de TI.",
    features: [
      "Catálogo público por escuela con buscador, inscritos, módulos y horas por curso.",
      "Aula virtual con reproductor de clases, contenido por módulos y archivos descargables por módulo.",
      "Panel administrativo con gestión de cursos (160+), usuarios, matrículas y evaluaciones.",
      "Generación de certificados masivos a partir de plantillas.",
      "Módulo de reclamos y validación pública de certificados.",
      "Reportes, logs de actividad y roles de administración (incluido super admin).",
      "Integración con Moodle y blog corporativo.",
      "Almacenamiento de archivos en Cloudflare R2 y video transcodificado con streaming adaptativo.",
    ],
    highlights: [
      "Migración desde una plataforma heredada a una arquitectura modular, con independencia entre cursos y salas.",
      "Reducción de quejas por tiempos de carga tras reemplazar los MP4 por streaming transcodificado.",
    ],
    media: [
      {
        type: "image",
        url: "/experiencias/ccd/plataforma-ccd.webp",
        caption: "Aula virtual: reproductor de clase y contenido del curso por módulos",
      },
      {
        type: "image",
        url: "/experiencias/ccd/home-ccd.webp",
        caption: "Catálogo público de cursos y diplomas",
      },
      {
        type: "image",
        url: "/experiencias/ccd/admin-ccd.webp",
        caption: "Panel administrativo: gestión de cursos, certificados masivos y evaluaciones",
      },
      {
        type: "image",
        url: "/experiencias/ccd/desarrolladores-ccd.webp",
        caption: "Página del equipo de desarrollo",
      },
    ],
  },
  {
    id: "proj-011",
    title: "E-Learning Digital College",
    description: "Plataforma e-learning gamificada para escolares: minijuegos, simulaciones interactivas, perfiles personalizables y tienda de recompensas.",
    technologies: [TECHNOLOGIES.angular, TECHNOLOGIES.express, TECHNOLOGIES.nodejs, TECHNOLOGIES.mysql],
    category: ["FULLSTACK"],
    year: 2024,
    demoUrl: "https://www.digitalcollege.edu.pe/",
    company: "Centro de Capacitación y Desarrollo",
    role: "Líder de desarrollo",
    imageUrl: "/proyectos/digital-college/plataforma-dc.webp",
    longDescription:
      "Plataforma e-learning para primaria y secundaria que combina el contenido académico con gamificación: los alumnos avanzan por niveles ganando experiencia, monedas y diamantes, y aprenden de forma interactiva con minijuegos y simulaciones en lugar de solo leer o ver videos.\n\nCada usuario tiene un perfil propio que puede personalizar con avatar, marco, banner, fondo, tarjetas e insignias, comprados en la tienda con la moneda que gana estudiando. Lideré su desarrollo desde el área de TI del Centro de Capacitación y Desarrollo.",
    features: [
      "Biblioteca de libros/cursos por grado (4to de primaria a 5to de secundaria), organizados por bimestre.",
      "Gamificación con niveles, experiencia, racha diaria, monedas y diamantes.",
      "Minijuegos y simulaciones (labs interactivos) para aprender de forma práctica.",
      "Campus Trivia: trivia de conocimiento académico.",
      "Perfil personalizable: avatar, marcos, wallpaper, banners, tarjetas, video, insignias y grupo.",
      "Tienda para canjear monedas y diamantes por personalización o por productos reales.",
      "Ranking de estudiantes por experiencia acumulada (general, primaria y secundaria).",
      "Seguimiento de avance por curso y anuncios de novedades y eventos.",
      "Landing pública por grado con el catálogo de cursos.",
    ],
    media: [
      {
        type: "image",
        url: "/proyectos/digital-college/plataforma-dc.webp",
        caption: "Plataforma del alumno: nivel, experiencia, racha, monedas y sus libros",
      },
      {
        type: "image",
        url: "/proyectos/digital-college/curso-dc.webp",
        caption: "Vista de curso con contenido por bimestre, avance y libro virtual",
      },
      {
        type: "image",
        url: "/proyectos/digital-college/tienda-dc.webp",
        caption: "Tienda: avatares, marcos, fondos y banners por rareza",
      },
      {
        type: "image",
        url: "/proyectos/digital-college/perfil-dc.webp",
        caption: "Editor de perfil: avatar, marcos, wallpaper, banners e insignias",
      },
      {
        type: "image",
        url: "/proyectos/digital-college/landing-dc.webp",
        caption: "Landing pública de Digital College",
      },
      {
        type: "image",
        url: "/proyectos/digital-college/grado-dc.webp",
        caption: "Catálogo de cursos por grado",
      },
    ],
  },
  {
    id: "proj-012",
    title: "LazyCF",
    description: "TUI en Rust estilo lazydocker para administrar Cloudflare — DNS, Túneles, Workers, Queues, D1 y R2 — sin salir de la terminal.",
    technologies: [TECHNOLOGIES.rust, TECHNOLOGIES.ratatui, TECHNOLOGIES.r2],
    category: ["TOOL", "BACKEND"],
    year: 2025,
    status: "EN PRODUCCION",
    repoUrl: "https://github.com/PaulPPS632/lazycf",
    demoUrl: "https://lazycf.paulp.dev/",
    imageUrl: "/proyectos/lazycf/web-lazycf.webp",
    longDescription:
      "Interfaz de terminal inspirada en lazydocker, escrita en Rust con ratatui, para operar una cuenta de Cloudflare sin abrir el dashboard web. Seis módulos —DNS/Dominios, Túneles Zero Trust, Workers, Queues, D1 y R2— con navegación por paneles y atajos de teclado.\n\nTodas las llamadas a la API son async, así que la UI nunca se bloquea, y el render es bajo demanda: CPU ≈ 0 en reposo. Soporta multi-cuenta y multi-token, con las credenciales guardadas en el keyring del sistema, nunca en texto plano. Se instala con `npm install -g lazycf`, que baja el binario nativo para Linux, macOS (Intel y Apple Silicon) o Windows.",
    features: [
      "DNS: zonas y registros con formulario dinámico por tipo (A, AAAA, CNAME, TXT, MX), toggle de proxy y purga de caché.",
      "Túneles Zero Trust: estado en vivo por datacenter, rutas públicas de ingress que crean el CNAME automáticamente.",
      "Workers: métricas 24h, historial de deployments con rollback, variables y secretos, rutas y live-tail de logs por WebSocket.",
      "Queues: consumers editables, envío y peek de mensajes, pausar/purgar, sparklines de backlog.",
      "D1: editor SQL multilínea con autocompletado contextual, LIMIT automático y resultados en rejilla navegable por celda.",
      "R2: navegador de objetos con búsqueda profunda, subida/descarga, URLs prefirmadas SigV4, CORS y preview de imágenes en la terminal.",
      "Autenticación por OAuth de Cloudflare o API token, con credenciales en el keyring del sistema.",
      "Multi-cuenta con selector activo, tres temas (Cloudflare, Everforest, Tokyo Night), soporte completo de mouse y ayuda contextual.",
    ],
    media: [
      {
        type: "image",
        url: "/proyectos/lazycf/web-lazycf.webp",
        caption: "Landing del proyecto",
      },
      {
        type: "image",
        url: "/proyectos/lazycf/onboarding-lazycf.webp",
        caption: "Onboarding: login por OAuth o API token",
      },
      {
        type: "image",
        url: "/proyectos/lazycf/dns-lazycf.webp",
        caption: "Módulo DNS: zonas y registros de la zona activa",
      },
      {
        type: "image",
        url: "/proyectos/lazycf/dns_2-lazycf.webp",
        caption: "DNS: formulario dinámico por tipo de registro",
      },
      {
        type: "image",
        url: "/proyectos/lazycf/tuneles-lazycf.webp",
        caption: "Túneles Zero Trust con estado en vivo y rutas de ingress",
      },
      {
        type: "image",
        url: "/proyectos/lazycf/workers-lazycf.webp",
        caption: "Workers: scripts y métricas de 24 h",
      },
      {
        type: "image",
        url: "/proyectos/lazycf/workers_2-lazycf.webp",
        caption: "Workers: live-tail de logs por WebSocket",
      },
      {
        type: "image",
        url: "/proyectos/lazycf/queues-lazycf.webp",
        caption: "Queues: consumers, backlog y envío de mensajes",
      },
      {
        type: "image",
        url: "/proyectos/lazycf/d1-lazycf.webp",
        caption: "D1: editor SQL con autocompletado y rejilla de resultados",
      },
      {
        type: "image",
        url: "/proyectos/lazycf/r2-lazycf.webp",
        caption: "R2: buckets, uso y navegador de objetos",
      },
      {
        type: "image",
        url: "/proyectos/lazycf/multicuenta-lazycf.webp",
        caption: "Selector de cuenta activa (multi-cuenta y multi-token)",
      },
    ],
  },
  {
    id: "proj-013",
    title: "LLEGO",
    description: "Seguimiento en vivo de los buses del corredor complementario de Lima: rutas, paraderos y posiciones de las líneas amarilla, azul, roja y morada.",
    technologies: [
      TECHNOLOGIES.nextjs,
      TECHNOLOGIES.typescript,
      TECHNOLOGIES.supabase,
      TECHNOLOGIES.postgresql,
      TECHNOLOGIES.maplibre,
    ],
    category: ["FULLSTACK"],
    year: 2025,
    status: "EN PRODUCCION",
    repoUrl: "https://github.com/PaulPPS632/llego-web",
    demoUrl: "https://llego.paulp.dev/",
    imageUrl: "/proyectos/llego/mapa-llego.webp",
    longDescription:
      "Servicio web para hacerle seguimiento a los corredores complementarios de Lima —líneas amarilla, azul, roja y morada— con sus 31 rutas, sus dos sentidos, sus paraderos y la posición de los buses actualizada cada 20 segundos. No hay nada que instalar y el catálogo se ve sin cuenta; la sesión con Google solo sirve para guardar favoritos.\n\nEl reparto de responsabilidades es explícito: el catálogo y los favoritos viven en Supabase (Postgres con RLS) y las posiciones llegan de un microservicio de telemetría aparte (Redis + FastAPI) que la web consume por un Route Handler propio, para que la API key nunca llegue al navegador.",
    features: [
      "Mapa en vivo con hasta 6 rutas simultáneas sobre MapLibre y teselas de OpenFreeMap (sin API key).",
      "Posiciones refrescadas cada 20 s, interpoladas 2,5 s hacia la nueva captura — sin extrapolar: un bus detenido no se dibuja tres cuadras más allá.",
      "Cada bus es un círculo del color de su línea, con flecha de rumbo solo cuando el AVL lo reporta.",
      "Estado explícito por captura (ok, sin datos, vencida, inválida): una falta de datos nunca se lee como una ruta sin buses.",
      "Selección de rutas guardada en la URL, así un enlace compartido abre el mapa ya armado.",
      "\"Cerca de mí\": filtra rutas con buses a 500 m / 1 km / 2 km, con la ubicación resuelta solo en el navegador.",
      "Catálogo de 31 rutas por línea y sentido, con buscador y paraderos por ruta.",
      "Favoritos por persona con login de Google (Supabase Auth, flujo PKCE y RLS).",
      "Tema claro/oscuro resuelto en el servidor por cookie, sin parpadeo al hidratar.",
    ],
    media: [
      {
        type: "image",
        url: "/proyectos/llego/mapa-llego.webp",
        caption: "Mapa en vivo con cuatro rutas y sus buses",
      },
      {
        type: "image",
        url: "/proyectos/llego/home-llego.webp",
        caption: "Portada con el tablero de líneas",
      },
      {
        type: "image",
        url: "/proyectos/llego/rutas-llego.webp",
        caption: "Catálogo de rutas del corredor con buscador y favoritos",
      },
      {
        type: "image",
        url: "/proyectos/llego/selector-llego.webp",
        caption: "Selector de rutas por línea y sentido",
      },
    ],
  },
  {
    id: "proj-014",
    title: "Minand",
    description: "Plugin para Omarchy que arranca y detiene emuladores de Android desde la barra, sin abrir Android Studio.",
    technologies: [TECHNOLOGIES.qml, TECHNOLOGIES.javascript, TECHNOLOGIES.bash],
    category: ["TOOL"],
    year: 2025,
    status: "EN DESARROLLO",
    repoUrl: "https://github.com/PaulPPS632/minand",
    imageUrl: "/proyectos/minand/list-avds-minand.webp",
    longDescription:
      "Widget de la barra de Omarchy (Quattro) para manejar los emuladores de Android sin abrir Android Studio: el ícono lleva la cuenta de cuántos están corriendo y el panel lista los AVDs, los lanza, los detiene y crea nuevos. El nombre sale de \"mini android\": Min(i) + And(roid).\n\nQML, JavaScript y siete scripts de shell pequeños — sin paso de build ni binario que instalar. El panel se refresca cada 3 segundos mientras está abierto y cada 20 cuando no.",
    features: [
      "Cuenta de emuladores corriendo en el ícono de la barra y estado por AVD en el panel.",
      "Lanzar un AVD con Enter o click; el emulador queda desacoplado y sobrevive al shell.",
      "Detener un AVD con apagado ordenado del guest (no una señal), armado con doble `x` y barra de 3 s en vez de un modal que robe el foco.",
      "Crear AVDs en dos pasos: catálogo de dispositivos leído de `sdklib.jar` —el mismo de Android Studio— filtrable por texto y factor de forma, luego imagen de sistema y nombre propuesto automáticamente.",
      "Filtro de AVDs y navegación completa por teclado (j/k, /, n, r, g/G, Esc).",
      "Estado vacío que nombra el problema y su solución cuando falta el SDK, en vez de una lista vacía.",
    ],
    media: [
      {
        type: "image",
        url: "/proyectos/minand/list-avds-minand.webp",
        caption: "Lista de AVDs en la barra, con los que están corriendo marcados",
      },
      {
        type: "image",
        url: "/proyectos/minand/new-avds-minand.webp",
        caption: "Catálogo de dispositivos para crear un AVD, filtrado por factor de forma",
      },
    ],
  },
  {
    id: "proj-015",
    title: "R2 Manager",
    description: "Gestor web de buckets de Cloudflare R2, pensado para que cualquiera lo despliegue en su propio Worker y apunte a su bucket.",
    technologies: [
      TECHNOLOGIES.nuxt,
      TECHNOLOGIES.typescript,
      TECHNOLOGIES.tailwind,
      TECHNOLOGIES.workers,
      TECHNOLOGIES.r2,
    ],
    category: ["TOOL", "FULLSTACK"],
    year: 2026,
    status: "EN DESARROLLO",
    repoUrl: "https://github.com/PaulPPS632/R2-MANAGER",
    demoUrl: "https://r2-manager.paulp.dev/",
    imageUrl: "/proyectos/r2-manager/raiz-r2m.webp",
    longDescription:
      "Gestor de archivos para Cloudflare R2 hecho con Nuxt 4 y Nuxt UI: explorar, subir, borrar y organizar objetos y carpetas de un bucket desde el navegador, con previsualización de imágenes, video y audio.\n\nLa idea es que cualquiera pueda levantarlo: clonas, despliegas en un Worker de Cloudflare, configuras los secrets apuntando a tu bucket y ya tienes un gestor web de tu R2. Las operaciones de lectura y borrado usan el binding nativo de R2 en el Worker; las credenciales S3 solo se usan para firmar Presigned URLs, así que la subida va directa del navegador a R2 sin pasar por el servidor.\n\nHoy no tiene roles ni permisos —está en la lista para la siguiente versión—, así que la instancia desplegada es de quien la despliega.",
    features: [
      "Navegación por carpetas con breadcrumbs y contador de carpetas/objetos.",
      "Subida por Presigned URL: PUT directo del navegador a R2, sin pasar el archivo por el Worker.",
      "Creación de carpetas usando un `.keep` como placeholder.",
      "Eliminación de objetos con confirmación.",
      "Previsualización en modal de imágenes, video y audio.",
      "Miniaturas de imágenes con Cloudflare Image Resizing.",
      "Vista en lista o en cuadrícula, y modo claro/oscuro.",
      "Despliegue propio: `wrangler secret put` con tu cuenta y bucket, `pnpm deploy:cf` y listo.",
    ],
    media: [
      {
        type: "image",
        url: "/proyectos/r2-manager/raiz-r2m.webp",
        caption: "Raíz del bucket en vista de lista",
      },
      {
        type: "image",
        url: "/proyectos/r2-manager/lista-r2m.webp",
        caption: "Carpeta con objetos: nombre, tamaño y fecha",
      },
      {
        type: "image",
        url: "/proyectos/r2-manager/grid-r2m.webp",
        caption: "Vista en cuadrícula con miniaturas",
      },
      {
        type: "image",
        url: "/proyectos/r2-manager/dark-r2m.webp",
        caption: "Modo oscuro",
      },
    ],
  },
  {
    id: "proj-016",
    title: "SEGURITO",
    description: "SaaS de gestión de Seguridad y Salud en el Trabajo: inspecciones desde el móvil, documentos SST y firma de declaraciones juradas.",
    technologies: [
      TECHNOLOGIES.nextjs,
      TECHNOLOGIES.reactnative,
      TECHNOLOGIES.nestjs,
      TECHNOLOGIES.typescript,
      TECHNOLOGIES.postgresql,
    ],
    category: ["FULLSTACK"],
    year: 2026,
    status: "EN DESARROLLO",
    demoUrl: "https://segurito.app",
    company: "ICOCERT",
    role: "Desarrollador Full Stack",
    imageUrl: "/proyectos/segurito/modulos-segurito.webp",
    longDescription:
      "SaaS integral para gestionar el Sistema de Gestión de Seguridad y Salud en el Trabajo, alineado a ISO 45001, y generar la documentación lista para el SIG. La captura ocurre en campo desde el móvil y la supervisión desde el panel web, con la misma información separada por empresa, sede y frente.\n\nEl espacio de trabajo se arma por módulos agrupados en tres familias —Seguridad y Salud, Operaciones y Administración— y todo lo que emiten esos módulos aterriza en un repositorio de documentos listo para entregar en auditoría.\n\nLo desarrollé de forma autónoma: app móvil en React Native, web en Next.js y backend en NestJS. Actualmente está en marcha blanca en producción.",
    features: [
      "Módulos por familia: Gestión SST, Riesgos (IPERC, ATS, PETAR), Eventos, Simulacros, Registro de actividad, Gestión logística, Maquinaria y equipos, RRHH, Capacitaciones, Documentos, Empresa y sedes, Miembros y roles.",
      "Inspecciones desde el móvil con evidencia fechada, ubicación validada y responsable.",
      "Centro de documentos con todo lo emitido por cada módulo, contador de evidencia lista para auditoría y descarga masiva.",
      "Firma de declaraciones juradas dentro del flujo, con sección propia de \"Mi firma\".",
      "Indicadores de RRHH: personal propio y tercerizado por mes, índice de documentos firmados por tipo de declaración y avance del programa anual de capacitación.",
      "Notificaciones en tiempo real sobre pendientes y alertas.",
      "Multiempresa y multisede, con roles y permisos por miembro.",
      "Repositorio aparte para certificados, pólizas y contratos que la empresa recibe de afuera.",
    ],
    highlights: [
      "Desarrollado de forma autónoma en sus tres frentes: móvil (React Native), web (Next.js) y backend (NestJS).",
      "En marcha blanca en producción, liderando la fase de pruebas.",
    ],
    media: [
      {
        type: "image",
        url: "/proyectos/segurito/modulos-segurito.webp",
        caption: "Centro de trabajo: módulos agrupados por familia",
      },
      {
        type: "image",
        url: "/proyectos/segurito/documentos-segurito.webp",
        caption: "Documentos: todo lo emitido por los módulos, listo para entregar en auditoría",
      },
      {
        type: "image",
        url: "/proyectos/segurito/indicadores-segurito.webp",
        caption: "Indicadores de RRHH: personal, documentos firmados y programa de capacitación",
      },
      {
        type: "image",
        url: "/proyectos/segurito/plataforma-segurito.webp",
        caption: "Captura en campo desde el móvil: inspección con evidencia y ubicación",
      },
      {
        type: "image",
        url: "/proyectos/segurito/home-segurito.webp",
        caption: "Portada del producto",
      },
      {
        type: "image",
        url: "/proyectos/segurito/como-segurito.webp",
        caption: "Cómo funciona el flujo de trabajo",
      },
    ],
  },
  {
    id: "proj-017",
    title: "AUDITORÍA 24/7",
    description: "Plataforma de auditoría continua con IA: analiza documentos del SIG contra los requisitos ISO y devuelve un reporte de hallazgos conformes y no conformes.",
    technologies: [
      TECHNOLOGIES.nextjs,
      TECHNOLOGIES.typescript,
      TECHNOLOGIES.rag,
      TECHNOLOGIES.workers,
      TECHNOLOGIES.postgresql,
    ],
    category: ["FULLSTACK"],
    year: 2026,
    status: "EN PRODUCCION",
    demoUrl: "https://auditoria247.com/",
    company: "ICOCERT",
    role: "Desarrollador Full Stack",
    imageUrl: "/proyectos/auditoria247/hallazgos-auditoria.webp",
    longDescription:
      "Plataforma que automatiza la gestión documental y el seguimiento de conformidad ISO. Sube documentos del SIG —o documentos cualquiera— y la IA los compara contra los requisitos de la norma, devolviendo un reporte con los hallazgos que cumplen y los que no, cláusula por cláusula.\n\nCada requisito queda clasificado —no conformidad mayor o menor, auditoría complementaria, sin evidencia, observación, oportunidad de mejora, cumple o no aplica— y de ahí sale el score de cumplimiento de la empresa y su informe de auditoría en PDF.\n\nLlevé el MVP web a producción en mis primeras dos semanas en ICOCERT y después reestructuré el motor de IA: un filtrado semántico de alta precisión que hace match entre los embeddings de los documentos y los requerimientos ISO (RAG), sobre Cloudflare Workers y Queues.",
    features: [
      "Análisis de documentos contra los requisitos de la norma, con el resultado ordenado por norma y por cláusula.",
      "Ocho clasificaciones por requisito, separadas según quién debe actuar: las que piden respuesta de la empresa, las recomendaciones del auditor y las que no requieren nada.",
      "Score de cumplimiento por empresa y por norma, con distribución de resultados y reclasificación masiva de hallazgos.",
      "Panel de auditor líder multiempresa: cumplimiento promedio, pendientes, plazos vencidos y empresas en foco por rango de fechas.",
      "Métricas del proceso: evolución de aperturas vs. cierres, estado del flujo de informes, tasa de subsanación, aprobación del PAC y tiempo de clasificación.",
      "Carga de trabajo por auditor y reasignación de auditorías.",
      "Informe de auditoría descargable en PDF y resumen aparte.",
      "Filtrado semántico por embeddings entre documentos y requerimientos ISO (RAG), procesado en background con Cloudflare Workers y Queues.",
      "Verificación pública de certificados.",
    ],
    highlights: [
      "MVP web en producción en las primeras 2 semanas, destrabando el desarrollo y asegurando la continuidad del producto.",
      "80% menos costo por auditoría gracias al filtrado semántico de alta precisión.",
      "Tiempo de procesamiento por auditoría de 1-2 horas a 20-30 minutos tras reestructurar el motor de IA con Workers y Queues.",
    ],
    media: [
      {
        type: "image",
        url: "/proyectos/auditoria247/hallazgos-auditoria.webp",
        caption: "Hallazgos de la auditoría por norma y cláusula, con su clasificación",
      },
      {
        type: "image",
        url: "/proyectos/auditoria247/panel-auditoria.webp",
        caption: "Panel de auditor líder: cumplimiento, pendientes y métricas del proceso",
      },
      {
        type: "image",
        url: "/proyectos/auditoria247/informe-auditoria.webp",
        caption: "Resultado de una auditoría ISO 9001, requisito por requisito",
      },
      {
        type: "image",
        url: "/proyectos/auditoria247/home-auditoria.webp",
        caption: "Portada con el panel de cumplimiento por norma",
      },
      {
        type: "image",
        url: "/proyectos/auditoria247/flujo-auditoria.webp",
        caption: "Flujo de la auditoría continua",
      },
      {
        type: "image",
        url: "/proyectos/auditoria247/precios-auditoria.webp",
        caption: "Planes del producto",
      },
    ],
  }
];
